### ISSUE TITLE
Stylise the pdf and make it more appealing 

### ISSUE THREAD

**Issue by drigio** [vaibhawvipul/First-steps-towards-Deep-Learning#9]
Currently the pdf that is being generated doesn't have good styling. It would be great to make the book look appealing so that readers feel interested.

Would love to work on it if possible! :)

**Comment by vaibhawvipul** [comment]
Sure. If you want to take this issue up then please go ahead! :)

**Comment by drigio** [comment]
<img src="https://user-images.githubusercontent.com/22986282/68947803-59dbd480-07dc-11ea-98ca-c45b984fe419.png" >


How about such a style?

**Comment by vaibhawvipul** [comment]
@drigio The design looks quite neat
